"""empty message

Revision ID: 696fcd5d143c
Revises: 1d581e440456
Create Date: 2021-09-26 03:30:13.839400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696fcd5d143c'
down_revision = '1d581e440456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')

    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
